### PR TITLE
Replace flatpickr for bulma-calendar

### LINKED ISSUE #223: Replace flatpickr in new group
#### Problem:
Right now flatpickr behaves not so well on mobiles: Android browsers Chrome and Firefox didn't use flatpickr, rather the OS native datetime picker. This makes it possible to create event in the past, and uses ISO date string in the form.

#### Solution:
1. Force from native to use flatpickr: https://flatpickr.js.org/mobile-support/ (They don't recommend it.)
2. Have a look at bulma calendar, demo here: https://creativebulma.net/product/calendar/demo (They made it responsive)

### PR DESCRIPTION
**Pull request by triszt4n**
Closes #223 

#### What's new:
* Flatpickr removed, Bulma-calendar is implemented instead
* Old functionalities are staying (range checking and preloading)

### CODE REVIEW

**Comment by OmTheTurtle** [comment]
For me, on mobile the picker behaves weird, it opens both and can't close them (tested on Chrome and Firefox dev tools).

**Comment by triszt4n** [comment]
> For me, on mobile the picker behaves weird, it opens both and can't close them (tested on Chrome and Firefox dev tools).

Yeah, gave me a headache. Consulted bulma-calendar creator, gonna mend it on Friday (gonna be a rough week).

**Comment by triszt4n** [comment]
Right now all of bulma will be imported in main.scss, as the modals are working complex with other parts of bulma.

**Comment by triszt4n** [comment]
This PR is a mess (merge conflicts again), gonna close it, see #291 for further development.

**Pull request closed without merging**
