### PR TITLE
Fix possible overflow problems if too long words

### PR DESCRIPTION
**Pull request by triszt4n**
### Summary:
Just noticed these little problems, that might occur, if the user is *completely evil and/or stupid* and writes everything into one huge word. This PR introduces a solution to these, but this is an optional fix, we can dismiss it of course if it's unneccesary.

**Beispiel#1:**
Screenshot 2020-07-11 17 47 16

**Beispiel#2:**
Screenshot 2020-07-11 17 47 28

### CODE REVIEW

**Comment by triszt4n** [comment]
Yep, the `flex: unset;` one is definitely needed, this would be the title without it:
image

**Comment by OmTheTurtle** [comment]
Can you move the style to dedicated CSS classes in `additions.scss`? Inline styles don't scale well, and also, I think we should apply these fixes to ticket layout too.

**Comment by triszt4n** [comment]
Applied suggestions (thanks, it was a good idea!). I guess, the ticket layout works well with long words.

**Comment by triszt4n** [comment]
So. Applied all suggestions, and got rid of unuseful group.scss, as we have spacing helpers and now a brand new `break-long-words` class, which got applied onto group and ticket cards' content. Will be useful for later use. (Will need a squash after these commits, I guess?)

**Pull request merged**
